### PR TITLE
[Enhancement] Add Special Handling of Rust Project Files; fixes #390

### LINKED ISSUE #390: [Bug Report] Automatic Version increase overwrite the version from all crates in cargo.lock
While using the new feature to increase the version manually [Commit link](https://github.com/AmmarAbouZor/tui-journal/commit/20414952cc29369b4083083091db8fbcf36d8417) I ran to the issue that not only the version of my app has been overwritten, but also all the crates with a version matching the current version of my app.

I assume that the tool makes a search and replacement through the whole file which caused this problem. I'll suggest using TOML parser to replace the version in the app section only

### PR DESCRIPTION
**Pull request by kevinmatthes**

### CODE REVIEW

File: src/increment_version.rs [hunk 1]
```diff
@@ -0,0 +1,182 @@
...
+
+      if edited {
+        file.truncate(Box::new(lock_file.clone().to_string()))
+      } else {
+        Err(ExitCode::DataErr)
+      }
+    } else {
+      Err(ExitCode::Usage)
+    }
+  }
```
Comment (kevinmatthes) [inline src/increment_version.rs:151]: *Any* file named `Cargo.lock` will be updated as follows:

- Aeruginous searches for the given package name in the respective `Cargo.lock` and updates exclusively that package's version.
- If no such package is given in the respective `Cargo.toml`, the update will fail.
- If *any* file named `Cargo.lock` is given but no package name is specified, the update will fail.

File: src/increment_version.rs [hunk 2]
```diff
@@ -0,0 +1,182 @@
...
+        file.truncate(Box::new(manifest.to_string()))?;
+
+        Ok(())
+      } else {
+        Err(ExitCode::DataErr)
+      }
+    } else {
+      Err(ExitCode::DataErr)
+    }
+  }
```
Comment (kevinmatthes) [inline src/increment_version.rs:168]: *Any* file named `Cargo.toml` will be updated as follows:

- Aeruginous searches for the `package.version` field and updates exclusively that value.
- If no version field is present in the respective `Cargo.toml`, the update will fail.

File: src/increment_version.rs [hunk 3]
```diff
@@ -0,0 +1,182 @@
...
+  fn update_normal_file(&self, file: &PathBuf) -> Result<()> {
+    file.truncate(Box::new(
+      file
+        .read()?
+        .try_into_string()?
+        .split(&self.old_version)
+        .collect::<Vec<&str>>()
+        .join(&self.new_version),
+    ))
+  }
```
Comment (kevinmatthes) [inline src/increment_version.rs:179]: *Any* file which neither a `Cargo.lock` nor a `Cargo.toml` will be updated as follows:  Aeruginous searches for occurrences of the given version string and updates each.

**Review by kevinmatthes — COMMENTED** [review]
@AmmarAbouZor

Please tell me if you agree with this behaviour of Aeruginous for `Cargo.lock` and `Cargo.toml` files.

**Comment by kevinmatthes** [comment]
@AmmarAbouZor

As you already mentioned in #390, some warning messages should be printed in case that the version increment should fail.  I agree with you and will add them, in the following.

But in contrast to exiting with code zero for "okay", I would prefer to make the workflow calling Aeruginous fail as any of the of the reasons for the version increment to fail indicates major problems which should be solved even before generating the RONLOG / CHANGELOG because their resolution might be relevant enough for being documented in there.  Thus, I would like to suggest to leave the non-zero exiting behaviour in as a feature.  Furthermore, this would prevent the tracked files from becoming out of sync as the code base will be left in an undefined state if the version increment should fail; it is not always possible to check for the version increment to succeed beforehand as some error conditions are rather random.  Having to restart the entire workflow in case of an error will make sure that the code base will always be in a defined and known state.

**Comment by kevinmatthes** [comment]
@AmmarAbouZor

I added error messages to the logic; the keywords are highlighted in red.

File: src/increment_version.rs (hunk 2 above)
Comment (AmmarAbouZor) [reply src/increment_version.rs]: @kevinmatthes 
I'm afraid that overwriting the whole file would lead to remove any comments written inside the cargo.toml file or any commented-out configs. I ran into the same problem with Tui-Journal as I wanted to rewrite the config file there.

I suggest using the old logic (Changing the version manually) + Verifying the changes with toml parser would be enough for a simple use-case.

Increasing the version from the CLI seems to be a complicated issue [isse](https://github.com/rust-lang/cargo/issues/6583)

File: src/increment_version.rs (hunk 3 above)
Comment (AmmarAbouZor) [reply src/increment_version.rs:209]: It looks fine, but I'm a little pit curious here about using split-->collect-->join. Is this approach better than the normal replace method on a string?

**Comment by AmmarAbouZor** [comment]
@kevinmatthes 
I agree that having a problem here should be reported as an error with exit code. I would then suggest adding an option to skip increasing the version besides the current options `major, minor, patch` like `keep` or `skip`.

Blocking the pipeline because Aeruginous can't increase the version without giving an option to increase the version manually could block a release until changing the release pipeline itself and removing increase-version command from within the .yml file and the bring it back after that.

File: src/increment_version.rs (hunk 3 above)
Comment (kevinmatthes) [reply src/increment_version.rs:209]: You are right, the classic replacement is better.  I do not really remember why I decided to use this solution instead; I guess I assumed the performance would be better.

File: src/increment_version.rs (hunk 2 above)
Comment (kevinmatthes) [reply src/increment_version.rs]: I will add another mode:  rewriting.  In contrast to editing files to only change the necessary lines, rewriting shall also reformat the file.

**Comment by kevinmatthes** [comment]
@AmmarAbouZor

I implemented the changes you requested regarding the updating logic; you are now free to choose whether you would like to update or to rewrite the Cargo.toml, defaulting to a simple update without reformatting the file.

---

Regarding the exit codes in error cases, I disagree with you.  If Aeruginous should consider the situation impossible to continue, it is most likely that either:

- the Cargo.toml is invalid TOML (upload to crates.io would fail anyway; immediate fix required);
- the Cargo.lock is invalid (just recreate it to fix this); or
- there is a typo in the name of the Rust package you need to give to Aeruginous to make it update Cargo.lock, as well (fix the typo in the workflow file and `git grep` for the typo to find similar mistakes before releasing the next version with mistakes in the documentation).

These reasons are nearly impossibly rare if:

- the Cargo.toml is only edited manually with utmost caution as well as `cargo` to add further dependencies;
- the Cargo.lock is only edited with `cargo`, Dependabot and / or Renovate (a bot quite similar to Dependabot); and
- the crate's name is *not* changed over and over again.

Since these three conditions can be safely expected to be the normal style of developing a Rust project, the version increment on Cargo.lock and Cargo.toml would only fail if there are fundamental problems with the project's code base which require urgent fixes.  In addition to the error conditions named above, there are also the usual file IO errors which can happen with *any* software and the simplest way fixing them is to check if the software is called correctly and to try again.  Everything else is a bug which requires a bug report and deserves a fix.

**Comment by kevinmatthes** [comment]
@AmmarAbouZor

If you would like to continue the discussion on possible error causes during the release preparations, i.e. the RONLOG assembly, which might cause Aeruginous to block the release pipeline, please create a discussion of type "General" in the "Discussions" tab and explain the challenges you see with a concrete example.

**Comment by AmmarAbouZor** [comment]
@kevinmatthes 
Thanks for fixing it. We can try it out and gather more infos from the experience with it.
For now I think it should work as intended and for all use-cases I have in mind :100:
